#!/bin/bash -e
#
# Amazon AWS blocker through iptables.
#
# First we use curl to grab the official list of ranges from Amazon. The -s
# prevents extraneous output from curl, and the -L makes it follow redirects.
#
# The ranges are passed to jq, a JSON parser. The -r makes jq output raw data
# without quotes. We only need the list of prefixes, so we discard everything
# else.

DIR=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
. $DIR/functions.sh



JSON=$(get_aws_json $1)

if [[ -f $1 ]]; then
    shift
fi


# Get the line where the jump will be inserted at.
# Useful if you want e.g related / established rules for outgoing traffic.
if [[ -n $1 ]]; then
    POSITION=$1
    shift
else
    POSITION=1
fi

log "Inserting at position $POSITION"


FILTERS=$(build_filters "$*")


# IPv4
create_and_flush_chain "" $POSITION
V4_RANGES=$(extract_ip_ranges "$JSON" "$FILTERS" "prefixes" "ip_prefix")
add_iptables_rules ""  "$V4_RANGES"


# IPv6
create_and_flush_chain 6 $POSITION
V6_RANGES=$(extract_ip_ranges "$JSON" "$FILTERS" "ipv6_prefixes" "ipv6_prefix")
add_iptables_rules "6" "$V6_RANGES"
